### ISSUE TITLE
probably nothing: MalformedInputException

### ISSUE THREAD

**Issue by Teque5** [shatterhand19/RhythmboxPOPM#1]
I'm clearly a dunce when it comes to Java, but i'm getting hung up. I put a print at the top of POPMToRB `System.out.println(Arrays.toString(args));` to check if I was crazy, but i get the following output:

```
$ java POPMToRB /valid/location/**/01*.mp3
[/valid/location/album/01 - file.mp3]
Exception in thread "main" java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at java.nio.file.Files.readAllLines(Files.java:3205)
	at java.nio.file.Files.readAllLines(Files.java:3242)
	at POPMToRB.main(POPMToRB.java:41)
```
and line 41 is:
`args = Files.readAllLines(Paths.get(args[0])).get(0).split(",;");`

**Comment by shatterhand19** [comment]
Hi, sorry for seeing the issue just now. I have changed the Readme to reflect this - you have to specify global path.
Check if you get the same thing if you run it with the global path.

**Comment by Teque5** [comment]
Yeah it finds a lot of files, but I get the same error:

```
$ java POPMToRB ~/../../srv/media/Music/**/*.mp3
[/home/me/../../srv/media/Music/album1/validfiles.mp3, /home/me/../../srv/media/Music/album2/validfiles.mp3]
Exception in thread "main" java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at java.nio.file.Files.readAllLines(Files.java:3205)
	at java.nio.file.Files.readAllLines(Files.java:3242)
	at POPMToRB.main(POPMToRB.java:41)
```

**Comment by shatterhand19** [comment]
Are the files mounted on a network drive? Apart from that I have no idea why this would happen, I used it a few weeks back on my new computer and it worked perfectly. If it is still happening if you run it for a file in ~/Music/file.mp3, then I will look into it after a few days, now I am snowed under with work.

**Comment by Teque5** [comment]
Yeah even local files get the same error. 
openjdk version "1.8.0_162"
```
  master  ~  Source  RhythmboxPOPM  1  java POPMToRB ~/Source/R
hythmboxPOPM/test.mp3 
[/home/teque5/Source/RhythmboxPOPM/test.mp3]
Exception in thread "main" java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at java.nio.file.Files.readAllLines(Files.java:3205)
	at java.nio.file.Files.readAllLines(Files.java:3242)
	at POPMToRB.main(POPMToRB.java:41)
```

**Comment by shatterhand19** [comment]
Ok, thank you for the info, will look into it in a couple of days. Apparently the problem is with the charsets, but without expecting the code I can't say more.
Meanwhile what OS are you on and what Java version is installed on it?

**Comment by shatterhand19** [comment]
Could you also try this and post the output:
sudo apt install enca; enca -L none ~/Documents/.rbtopopm_temp.txt

**Comment by Teque5** [comment]
```
$ enca -L none ~/Documents/.rbtopopm_temp.txt
7bit ASCII characters
```
Ubuntu 16.04 & openjdk version "1.8.0_162"

**Comment by shatterhand19** [comment]
Ok, so I believe the problem is the encoding. I will push a new version that is converting this file to UTF-8 and then check again. Also, just in case, update to the latest version of openjdk, I don't know if you current is the latest.

**Comment by shatterhand19** [comment]
Strangely enough mine I just tested mine with a file that was 7bit ASCII and it worked. This is really peculiar. Have you tried pulling and reinstalling? Otherwise it does not make sense, the only difference is probably the JDK version (I have 9) and the OS (I am on 17.10). 
Could you run and let me know if the problem persists so I can look into it.
```
sudo apt install openjdk-9-jdk
```

**Comment by Teque5** [comment]
FYI I'm running all this locally; I'm not interested in the install portion.

When i update to openjdk9 i just get a longer error message
```
Exception in thread "main" java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(java.base@9-internal/CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(java.base@9-internal/StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(java.base@9-internal/StreamDecoder.java:178)
	at java.io.InputStreamReader.read(java.base@9-internal/InputStreamReader.java:185)
	at java.io.BufferedReader.fill(java.base@9-internal/BufferedReader.java:161)
	at java.io.BufferedReader.readLine(java.base@9-internal/BufferedReader.java:325)
	at java.io.BufferedReader.readLine(java.base@9-internal/BufferedReader.java:390)
	at java.nio.file.Files.readAllLines(java.base@9-internal/Files.java:3222)
	at java.nio.file.Files.readAllLines(java.base@9-internal/Files.java:3259)
	at POPMToRB.main(POPMToRB.java:42)
```
At this point I think I may just write a python script to do this when i get some free time.

**Comment by Teque5** [comment]
For anyone else looking for a solution, [i posted the python implementation gist here](https://gist.github.com/Teque5/69d5ece2003e7ea1f3c29daf01b411a2).

Currently works on mp3 & flac.
